# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/salvo/Dropbox/Projects/GRACy/GRACy_UI/genotyping.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1072, 668)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(540, 10, 211, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 80, 211, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(550, 160, 231, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(550, 240, 171, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 211, 20))
        self.label_6.setObjectName("label_6")
        self.outputFolderEntry = QtWidgets.QLineEdit(Form)
        self.outputFolderEntry.setGeometry(QtCore.QRect(540, 30, 361, 32))
        self.outputFolderEntry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputFolderEntry.setObjectName("outputFolderEntry")
        self.inputFileButton = QtWidgets.QPushButton(Form)
        self.inputFileButton.setGeometry(QtCore.QRect(400, 30, 112, 32))
        self.inputFileButton.setObjectName("inputFileButton")
        self.outputFolderButton = QtWidgets.QPushButton(Form)
        self.outputFolderButton.setGeometry(QtCore.QRect(920, 30, 112, 32))
        self.outputFolderButton.setObjectName("outputFolderButton")
        self.dbEntry = QtWidgets.QLineEdit(Form)
        self.dbEntry.setGeometry(QtCore.QRect(550, 100, 351, 32))
        self.dbEntry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbEntry.setObjectName("dbEntry")
        self.dbButton = QtWidgets.QPushButton(Form)
        self.dbButton.setGeometry(QtCore.QRect(920, 100, 112, 32))
        self.dbButton.setObjectName("dbButton")
        self.detectionThresholdEntry = QtWidgets.QLineEdit(Form)
        self.detectionThresholdEntry.setGeometry(QtCore.QRect(550, 180, 231, 32))
        self.detectionThresholdEntry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detectionThresholdEntry.setObjectName("detectionThresholdEntry")
        self.numThreadsEntry = QtWidgets.QLineEdit(Form)
        self.numThreadsEntry.setGeometry(QtCore.QRect(550, 260, 151, 32))
        self.numThreadsEntry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numThreadsEntry.setObjectName("numThreadsEntry")
        self.logArea = QtWidgets.QTextEdit(Form)
        self.logArea.setGeometry(QtCore.QRect(10, 350, 821, 291))
        self.logArea.setObjectName("logArea")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(700, 290, 201, 211))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("GRACy_easyinstall/src/GUI/IconsFinal/Classification.jpg"))
        self.label_7.setObjectName("label_7")
        self.genotypeButton = QtWidgets.QPushButton(Form)
        self.genotypeButton.setGeometry(QtCore.QRect(850, 570, 201, 32))
        self.genotypeButton.setObjectName("genotypeButton")
        self.plotButton = QtWidgets.QPushButton(Form)
        self.plotButton.setGeometry(QtCore.QRect(850, 610, 201, 32))
        self.plotButton.setObjectName("plotButton")
        self.selectedFilesArea = QtWidgets.QTextEdit(Form)
        self.selectedFilesArea.setGeometry(QtCore.QRect(10, 30, 381, 261))
        self.selectedFilesArea.setReadOnly(True)
        self.selectedFilesArea.setObjectName("selectedFilesArea")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(820, 160, 211, 20))
        self.label_8.setObjectName("label_8")
        self.minimumReadsEntry = QtWidgets.QLineEdit(Form)
        self.minimumReadsEntry.setGeometry(QtCore.QRect(820, 180, 211, 32))
        self.minimumReadsEntry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minimumReadsEntry.setObjectName("minimumReadsEntry")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Genotyping tool"))
        self.label.setText(_translate("Form", "Input files"))
        self.label_2.setText(_translate("Form", "Output folder"))
        self.label_3.setText(_translate("Form", "kmer database"))
        self.label_4.setText(_translate("Form", "Minimum genotype frequency"))
        self.label_5.setText(_translate("Form", "Number of threads"))
        self.label_6.setText(_translate("Form", "Log window"))
        self.outputFolderEntry.setText(_translate("Form", "No folder selected"))
        self.inputFileButton.setText(_translate("Form", "Select files"))
        self.outputFolderButton.setText(_translate("Form", "Open folder"))
        self.dbEntry.setText(_translate("Form", "mainDB_seqs_filtered.txt"))
        self.dbButton.setText(_translate("Form", "Change DB"))
        self.detectionThresholdEntry.setText(_translate("Form", "0.02"))
        self.numThreadsEntry.setText(_translate("Form", "8"))
        self.genotypeButton.setText(_translate("Form", "Genotype!"))
        self.plotButton.setText(_translate("Form", "Plot"))
        self.label_8.setText(_translate("Form", "Minimum number of reads"))
        self.minimumReadsEntry.setText(_translate("Form", "10"))

