# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Dropbox/Projects/GRACy/GRACy_UI/snpCalling.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1222, 580)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 20))
        self.label.setObjectName("label")
        self.inputFileButton = QtWidgets.QPushButton(Form)
        self.inputFileButton.setGeometry(QtCore.QRect(460, 30, 112, 32))
        self.inputFileButton.setObjectName("inputFileButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(600, 80, 191, 20))
        self.label_2.setObjectName("label_2")
        self.cdsFileEntry = QtWidgets.QLineEdit(Form)
        self.cdsFileEntry.setGeometry(QtCore.QRect(600, 100, 241, 32))
        self.cdsFileEntry.setObjectName("cdsFileEntry")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(600, 220, 191, 20))
        self.label_3.setObjectName("label_3")
        self.annotationFileEntry = QtWidgets.QLineEdit(Form)
        self.annotationFileEntry.setGeometry(QtCore.QRect(600, 240, 241, 32))
        self.annotationFileEntry.setObjectName("annotationFileEntry")
        self.cdsFileButton = QtWidgets.QPushButton(Form)
        self.cdsFileButton.setGeometry(QtCore.QRect(850, 100, 112, 32))
        self.cdsFileButton.setObjectName("cdsFileButton")
        self.annotationFileButton = QtWidgets.QPushButton(Form)
        self.annotationFileButton.setGeometry(QtCore.QRect(850, 240, 112, 32))
        self.annotationFileButton.setObjectName("annotationFileButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(600, 150, 191, 20))
        self.label_4.setObjectName("label_4")
        self.genomeFileEntry = QtWidgets.QLineEdit(Form)
        self.genomeFileEntry.setGeometry(QtCore.QRect(600, 170, 241, 32))
        self.genomeFileEntry.setObjectName("genomeFileEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(600, 10, 191, 20))
        self.label_5.setObjectName("label_5")
        self.genomeFileButton = QtWidgets.QPushButton(Form)
        self.genomeFileButton.setGeometry(QtCore.QRect(850, 170, 112, 32))
        self.genomeFileButton.setObjectName("genomeFileButton")
        self.outputFolderEntry = QtWidgets.QLineEdit(Form)
        self.outputFolderEntry.setGeometry(QtCore.QRect(600, 30, 241, 32))
        self.outputFolderEntry.setObjectName("outputFolderEntry")
        self.outputFolderButton = QtWidgets.QPushButton(Form)
        self.outputFolderButton.setGeometry(QtCore.QRect(850, 30, 112, 32))
        self.outputFolderButton.setObjectName("outputFolderButton")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1050, 10, 191, 20))
        self.label_6.setObjectName("label_6")
        self.numThreadsCombo = QtWidgets.QComboBox(Form)
        self.numThreadsCombo.setGeometry(QtCore.QRect(1110, 30, 90, 28))
        self.numThreadsCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numThreadsCombo.setObjectName("numThreadsCombo")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.numThreadsCombo.addItem("")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(1050, 80, 191, 20))
        self.label_7.setObjectName("label_7")
        self.baseQualityCombo = QtWidgets.QComboBox(Form)
        self.baseQualityCombo.setGeometry(QtCore.QRect(1110, 100, 90, 28))
        self.baseQualityCombo.setObjectName("baseQualityCombo")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.baseQualityCombo.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 191, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1000, 320, 201, 211))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("GRACy_easyinstall/src/GUI/IconsFinal/SNPcalling.jpg"))
        self.label_9.setObjectName("label_9")
        self.logArea = QtWidgets.QTextEdit(Form)
        self.logArea.setGeometry(QtCore.QRect(10, 320, 981, 241))
        self.logArea.setObjectName("logArea")
        self.runButton = QtWidgets.QPushButton(Form)
        self.runButton.setGeometry(QtCore.QRect(1000, 530, 201, 32))
        self.runButton.setObjectName("runButton")
        self.deduplicationCombo = QtWidgets.QComboBox(Form)
        self.deduplicationCombo.setGeometry(QtCore.QRect(1110, 170, 90, 28))
        self.deduplicationCombo.setObjectName("deduplicationCombo")
        self.deduplicationCombo.addItem("")
        self.deduplicationCombo.addItem("")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1020, 150, 191, 20))
        self.label_10.setObjectName("label_10")
        self.selectedFilesArea = QtWidgets.QTextEdit(Form)
        self.selectedFilesArea.setGeometry(QtCore.QRect(10, 30, 441, 251))
        self.selectedFilesArea.setObjectName("selectedFilesArea")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SNP calling tool"))
        self.label.setText(_translate("Form", "Input file"))
        self.inputFileButton.setText(_translate("Form", "Select files"))
        self.label_2.setText(_translate("Form", "CDS fasta file"))
        self.label_3.setText(_translate("Form", "Annotation gff file"))
        self.cdsFileButton.setText(_translate("Form", "Open file"))
        self.annotationFileButton.setText(_translate("Form", "Open file"))
        self.label_4.setText(_translate("Form", "Genome fasta file"))
        self.label_5.setText(_translate("Form", "Output folder"))
        self.genomeFileButton.setText(_translate("Form", "Open file"))
        self.outputFolderButton.setText(_translate("Form", "Open file"))
        self.label_6.setText(_translate("Form", "Number of threads"))
        self.numThreadsCombo.setItemText(0, _translate("Form", "1"))
        self.numThreadsCombo.setItemText(1, _translate("Form", "2"))
        self.numThreadsCombo.setItemText(2, _translate("Form", "3"))
        self.numThreadsCombo.setItemText(3, _translate("Form", "4"))
        self.numThreadsCombo.setItemText(4, _translate("Form", "5"))
        self.numThreadsCombo.setItemText(5, _translate("Form", "6"))
        self.numThreadsCombo.setItemText(6, _translate("Form", "7"))
        self.numThreadsCombo.setItemText(7, _translate("Form", "8"))
        self.numThreadsCombo.setItemText(8, _translate("Form", "9"))
        self.numThreadsCombo.setItemText(9, _translate("Form", "10"))
        self.numThreadsCombo.setItemText(10, _translate("Form", "11"))
        self.numThreadsCombo.setItemText(11, _translate("Form", "12"))
        self.numThreadsCombo.setItemText(12, _translate("Form", "13"))
        self.numThreadsCombo.setItemText(13, _translate("Form", "14"))
        self.numThreadsCombo.setItemText(14, _translate("Form", "15"))
        self.numThreadsCombo.setItemText(15, _translate("Form", "16"))
        self.numThreadsCombo.setItemText(16, _translate("Form", "17"))
        self.numThreadsCombo.setItemText(17, _translate("Form", "18"))
        self.numThreadsCombo.setItemText(18, _translate("Form", "19"))
        self.numThreadsCombo.setItemText(19, _translate("Form", "20"))
        self.numThreadsCombo.setItemText(20, _translate("Form", "21"))
        self.numThreadsCombo.setItemText(21, _translate("Form", "22"))
        self.numThreadsCombo.setItemText(22, _translate("Form", "23"))
        self.numThreadsCombo.setItemText(23, _translate("Form", "24"))
        self.label_7.setText(_translate("Form", "Base quality cutoff"))
        self.baseQualityCombo.setItemText(0, _translate("Form", "30"))
        self.baseQualityCombo.setItemText(1, _translate("Form", "31"))
        self.baseQualityCombo.setItemText(2, _translate("Form", "32"))
        self.baseQualityCombo.setItemText(3, _translate("Form", "33"))
        self.baseQualityCombo.setItemText(4, _translate("Form", "34"))
        self.baseQualityCombo.setItemText(5, _translate("Form", "35"))
        self.baseQualityCombo.setItemText(6, _translate("Form", "36"))
        self.baseQualityCombo.setItemText(7, _translate("Form", "37"))
        self.baseQualityCombo.setItemText(8, _translate("Form", "38"))
        self.baseQualityCombo.setItemText(9, _translate("Form", "39"))
        self.baseQualityCombo.setItemText(10, _translate("Form", "40"))
        self.baseQualityCombo.setItemText(11, _translate("Form", "29"))
        self.baseQualityCombo.setItemText(12, _translate("Form", "28"))
        self.baseQualityCombo.setItemText(13, _translate("Form", "27"))
        self.baseQualityCombo.setItemText(14, _translate("Form", "26"))
        self.baseQualityCombo.setItemText(15, _translate("Form", "25"))
        self.baseQualityCombo.setItemText(16, _translate("Form", "24"))
        self.baseQualityCombo.setItemText(17, _translate("Form", "23"))
        self.baseQualityCombo.setItemText(18, _translate("Form", "22"))
        self.baseQualityCombo.setItemText(19, _translate("Form", "21"))
        self.baseQualityCombo.setItemText(20, _translate("Form", "20"))
        self.baseQualityCombo.setItemText(21, _translate("Form", "19"))
        self.baseQualityCombo.setItemText(22, _translate("Form", "18"))
        self.baseQualityCombo.setItemText(23, _translate("Form", "17"))
        self.baseQualityCombo.setItemText(24, _translate("Form", "16"))
        self.baseQualityCombo.setItemText(25, _translate("Form", "15"))
        self.baseQualityCombo.setItemText(26, _translate("Form", "14"))
        self.baseQualityCombo.setItemText(27, _translate("Form", "13"))
        self.baseQualityCombo.setItemText(28, _translate("Form", "12"))
        self.baseQualityCombo.setItemText(29, _translate("Form", "11"))
        self.baseQualityCombo.setItemText(30, _translate("Form", "10"))
        self.baseQualityCombo.setItemText(31, _translate("Form", "9"))
        self.baseQualityCombo.setItemText(32, _translate("Form", "8"))
        self.baseQualityCombo.setItemText(33, _translate("Form", "7"))
        self.baseQualityCombo.setItemText(34, _translate("Form", "6"))
        self.baseQualityCombo.setItemText(35, _translate("Form", "5"))
        self.baseQualityCombo.setItemText(36, _translate("Form", "4"))
        self.baseQualityCombo.setItemText(37, _translate("Form", "3"))
        self.baseQualityCombo.setItemText(38, _translate("Form", "2"))
        self.baseQualityCombo.setItemText(39, _translate("Form", "1"))
        self.baseQualityCombo.setItemText(40, _translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Log area"))
        self.runButton.setText(_translate("Form", "Run"))
        self.deduplicationCombo.setItemText(0, _translate("Form", "Yes"))
        self.deduplicationCombo.setItemText(1, _translate("Form", "No"))
        self.label_10.setText(_translate("Form", "Perform deduplication"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

